using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace BitirmeBackend.Infrastructure.Persistence;

/// <summary>
/// Applies pending migrations on startup and realigns identity sequences. Seeding rows with
/// explicit Ids into PostgreSQL "GENERATED BY DEFAULT AS IDENTITY" columns does not advance
/// the backing sequence, so without this the first runtime insert would collide with seed keys.
/// </summary>
public static class DbInitializer
{
    private static readonly string[] SeededTables =
    [
        "Roles", "Departments", "JobRoles", "Competencies", "ModelVersions",
        "AssessmentCycles", "Employees", "Users", "Assessments", "AssessmentScores"
    ];

    public static async Task InitializeAsync(AppDbContext db)
    {
        try
        {
            await db.Database.MigrateAsync();
            await SyncIdentitySequencesAsync(db);
        }
        catch (Exception ex)
        {
            var logger = db.GetInfrastructure().GetRequiredService<ILoggerFactory>().CreateLogger("DbInitializer");
            logger.LogError(ex, "Database migration failed. App will continue without migration.");
        }
    }

    private static async Task SyncIdentitySequencesAsync(AppDbContext db)
    {
        foreach (var table in SeededTables)
        {
            var sql =
                $"SELECT setval(pg_get_serial_sequence('\"{table}\"', 'Id'), " +
                $"GREATEST((SELECT COALESCE(MAX(\"Id\"), 0) FROM \"{table}\"), 1))";
            await db.Database.ExecuteSqlRawAsync(sql);
        }
    }
}
