CORE_COMM_01	Core_Communication	Core	Behavioral Practice	High	24	1.00	1.70	{"title": "Structured Communication Fundamentals", "resource": "https://www.coursera.org/learn/effective-communication-strategies-and-skills", "description": "Mesaj netliği ve amaç belirleme üzerine haftalık pratikler.", "delivery_type": "Self-guided + Practice"}
CORE_COMM_02	Core_Communication	Core	Guided Exercise	Medium-High	16	1.80	2.50	{"title": "Effective Feedback Application", "resource": "https://www.youtube.com/watch?v=wtl5UrrgU8c", "description": "Açık ifade ve duygu yönetimi üzerine egzersizler.", "delivery_type": "Workshop"}
CORE_COMM_03	Core_Communication	Core	Micro Learning	Medium	8	2.60	3.20	{"title": "Clarity & Conciseness Tune-Up", "resource": "https://www.youtube.com/watch?v=npsJwLk5vjU", "description": "Mesajları sadeleştirme ve ana mesajı öne çıkarma alıştırmaları.", "delivery_type": "Digital Module"}
CORE_COMM_04	Core_Communication	Core	Reflection	Low	4	3.30	4.00	{"title": "Communication Self-Review", "resource": "https://www.youtube.com/watch?v=WESGDi_ajUU", "description": "İletişim örneklerini değerlendirme ve kısa analiz.", "delivery_type": "Self Reflection"}
CORE_TEAM_01	Core_Teamwork	Core	Behavioral Practice	High	24	1.00	1.70	{"title": "Collaboration Basics Immersion", "resource": "https://www.coursera.org/learn/mastering-team-dynamics", "description": "Takım içi rol paylaşımı ve ortak hedef takibi görevleri.", "delivery_type": "Guided Practice"}
CORE_TEAM_02	Core_Teamwork	Core	Scenario Based Learning	Medium-High	16	1.80	2.50	{"title": "Conflict Handling in Teams", "resource": "https://www.coursera.org/learn/conflict-resolution-skills", "description": "Anlaşmazlıklarda iş birliğini koruma üzerine senaryolar.", "delivery_type": "Workshop"}
CORE_TEAM_03	Core_Teamwork	Core	Micro Learning	Medium	8	2.60	3.20	{"title": "Effective Collaboration Habits", "resource": "https://www.youtube.com/watch?v=3boKz0Exros", "description": "Bilgi paylaşımı ve destek alışkanlıklarını güçlendirme.", "delivery_type": "Digital Module"}
CORE_TEAM_04	Core_Teamwork	Core	Reflection	Low	4	3.30	4.00	{"title": "Team Contribution Review", "resource": "https://hbr.org/2016/06/the-secrets-of-great-teamwork", "description": "Takım içindeki katkının ve destek düzeyinin öz değerlendirmesi.", "delivery_type": "Self Reflection"}
CORE_PROB_01	Core_ProblemSolving	Core	Analytical Practice	High	24	1.00	1.70	{"title": "Problem Decomposition Fundamentals", "resource": "https://www.coursera.org/learn/creative-problem-solving", "description": "Problemleri alt bileşenlerine ayırma çalışmaları.", "delivery_type": "Guided Practice"}
CORE_PROB_02	Core_ProblemSolving	Core	Scenario Based Learning	Medium-High	16	1.80	2.50	{"title": "Root Cause Analysis Practice", "resource": "https://www.youtube.com/watch?v=yhc-EPLcIaI", "description": "Yüzeysel belirtiler yerine temel nedenleri belirleme vakaları.", "delivery_type": "Workshop"}
CORE_PROB_03	Core_ProblemSolving	Core	Micro Learning	Medium	8	2.60	3.20	{"title": "Solution Evaluation Techniques", "resource": "https://www.ted.com/talks/tom_wujec_got_a_wicked_problem_first_tell_me_how_you_make_toast", "description": "Çözüm alternatiflerini değerlendirme alıştırmaları.", "delivery_type": "Digital Module"}
CORE_PROB_04	Core_ProblemSolving	Core	Reflection	Low	4	3.30	4.00	{"title": "Problem-Solving Self Review", "resource": "https://hbr.org/2012/09/are-you-solving-the-right-problem", "description": "Çözülen problemlerin yaklaşımını gözden geçirme.", "delivery_type": "Self Reflection"}
CORE_ADAPT_01	Core_Adaptability	Core	Behavioral Practice	High	24	1.00	1.70	{"title": "Change Readiness Foundations", "resource": "https://www.coursera.org/learn/adaptability-and-resiliency", "description": "Yeni durumlara uyum sağlama egzersizleri.", "delivery_type": "Guided Practice"}
CORE_ADAPT_02	Core_Adaptability	Core	Scenario Based Learning	Medium-High	16	1.80	2.50	{"title": "Responding to Change Scenarios", "resource": "https://www.ted.com/talks/natalie_fratto_3_ways_to_measure_your_adaptability_and_how_to_improve_it", "description": "Beklenmeyen durumlarda hızlı uyum senaryoları.", "delivery_type": "Workshop"}
CORE_ADAPT_03	Core_Adaptability	Core	Micro Learning	Medium	8	2.60	3.20	{"title": "Flexibility & Adjustment Skills", "resource": "https://www.coursera.org/learn/mindshift", "description": "Yaklaşım değiştirme becerilerini destekleyen içerikler.", "delivery_type": "Digital Module"}
CORE_ADAPT_04	Core_Adaptability	Core	Reflection	Low	4	3.30	4.00	{"title": "Adaptability Self Assessment", "resource": "https://hbr.org/2020/05/how-to-build-your-resilience", "description": "Değişimlere verilen tepkilerin öz analizi.", "delivery_type": "Self Reflection"}
CORE_TIME_01	Core_TimeManagement	Core	Behavioral Practice	High	24	1.00	1.70	{"title": "Time Awareness & Priority Reset", "resource": "https://www.coursera.org/learn/work-smarter-not-harder", "description": "Önceliklendirme ve planlama alışkanlığı kazandırma.", "delivery_type": "Guided Practice"}
CORE_TIME_02	Core_TimeManagement	Core	Scenario Based Learning	Medium-High	16	1.80	2.50	{"title": "Managing Competing Priorities", "resource": "https://todoist.com/productivity-methods/eisenhower-matrix", "description": "İşler arasında öncelik belirleme vakaları.", "delivery_type": "Workshop"}
CORE_TIME_03	Core_TimeManagement	Core	Micro Learning	Medium	8	2.60	3.20	{"title": "Efficiency & Focus Techniques", "resource": "https://www.ted.com/talks/laura_vanderkam_how_to_gain_control_of_your_free_time", "description": "Odaklanma ve işleri tamamlama uygulamaları.", "delivery_type": "Digital Module"}
CORE_TIME_04	Core_TimeManagement	Core	Reflection	Low	4	3.30	4.00	{"title": "Personal Time Review", "resource": "https://www.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator", "description": "Zaman kullanım alışkanlıklarının değerlendirilmesi.", "delivery_type": "Self Reflection"}
CORE_INIT_01	Core_Initiative	Core	Behavioral Practice	High	24	1.00	1.70	{"title": "Proactive Mindset Activation", "resource": "https://www.udemy.com/course/leadership-skills-build-an-ownership-mindset-for-growth", "description": "Sorumluluk alma ve aksiyon başlatma egzersizleri.", "delivery_type": "Guided Practice"}
CORE_INIT_02	Core_Initiative	Core	Scenario Based Learning	Medium-High	16	1.80	2.50	{"title": "Taking Ownership", "resource": "https://www.linkedin.com/learning/succeeding-with-an-ownership-and-accountability-mindset", "description": "Yönlendirme olmayan durumlarda sorumluluk senaryoları.", "delivery_type": "Workshop"}
CORE_INIT_03	Core_Initiative	Core	Micro Learning	Medium	8	2.60	3.20	{"title": "Opportunity Spotting Habits", "resource": "https://www.accaglobal.com/gb/en/technical-activities/uk-tech/in-practice-ezine-archive/in-practice-archive-2024/October/Three-tips-strengthen-opportunity-spotting-muscle.html", "description": "Geliştirme fırsatlarını fark etme içerikleri.", "delivery_type": "Digital Module"}
CORE_INIT_04	Core_Initiative	Core	Reflection	Low	4	3.30	4.00	{"title": "Initiative Self Check", "resource": "https://hbr.org/2019/08/when-to-take-initiative-at-work-and-when-not-to", "description": "Alınan inisiyatiflerin öz değerlendirmesi.", "delivery_type": "Self Reflection"}
CORE_ACCT_01	Core_Accountability	Core	Behavioral Practice	High	24	1.00	1.70	{"title": "Responsibility Ownership", "resource": "https://www.coursera.org/learn/accountability-employee-engagement", "description": "İşlerin sahiplenilmesi ve çözüm üretme.", "delivery_type": "Guided Practice"}
CORE_ACCT_02	Core_Accountability	Core	Scenario Based Learning	Medium-High	16	1.80	2.50	{"title": "Handling Mistakes", "resource": "https://www.udemy.com/course/accountability-at-the-workplace/", "description": "Hata durumlarında sorumluluk alma vakaları.", "delivery_type": "Workshop"}
CORE_ACCT_03	Core_Accountability	Core	Micro Learning	Medium	8	2.60	3.20	{"title": "Commitment Tracking Habits", "resource": "https://hbr.org/tip/2019/06/how-leaders-build-trust", "description": "Verilen sözleri takip etme alışkanlıkları.", "delivery_type": "Digital Module"}
CORE_ACCT_04	Core_Accountability	Core	Reflection	Low	4	3.30	4.00	{"title": "Accountability Self Review", "resource": "https://hbr.org/2022/02/3-strategies-for-holding-yourself-accountable", "description": "Sahiplenme düzeyinin analizi.", "delivery_type": "Self Reflection"}
CORE_LEARN_01	Core_LearningAgility	Core	Behavioral Practice	High	24	1.00	1.70	{"title": "Learning Habit Foundations", "resource": "https://www.coursera.org/learn/learning-how-to-learn", "description": "Yeni bilgi edinme ve işe uyarlama görevleri.", "delivery_type": "Guided Practice"}
CORE_LEARN_02	Core_LearningAgility	Core	Scenario Based Learning	Medium-High	16	1.80	2.50	{"title": "Learning from New Situations", "resource": "https://www.coursera.org/learn/mindshift", "description": "Bilinmeyen konularda hızlı öğrenme senaryoları.", "delivery_type": "Workshop"}
CORE_LEARN_03	Core_LearningAgility	Core	Micro Learning	Medium	8	2.60	3.20	{"title": "Continuous Improvement", "resource": "https://www.youtube.com/watch?v=eUfyfngF0pM", "description": "Kısa sürede bilgi edinme içerikleri.", "delivery_type": "Digital Module"}
CORE_LEARN_04	Core_LearningAgility	Core	Reflection	Low	4	3.30	4.00	{"title": "Learning Agility Self Check", "resource": "https://www.youtube.com/watch?v=DcnapnW7zjk", "description": "Yeni konuların işe yansıtılması analizi.", "delivery_type": "Self Reflection"}
DEPT_COMP1_01	Dept_Comp1	Department	PracticalTask	Medium	3	1.00	1.90	{"Operations": {"title": "Operasyon Planı (Ops_OperationsPlanning)", "resource": "https://www.smartsheet.com/content/operational-plan-templates", "delivery_type": "Task"}, "Technology": {"title": "PR Refactor (Tech_CodingQuality)", "resource": "https://github.com/dev-aritra/clean-code-developer-checklist", "delivery_type": "Task"}, "Human Resources": {"title": "İlan Metni (HR_Recruitment)", "resource": "https://www.shrm.org/topics-tools/tools/job-descriptions", "delivery_type": "Task"}, "Sales & Marketing": {"title": "Müşteri Pitch (Sales_SalesSkill)", "resource": "https://blog.hubspot.com/sales/sales-pitch-examples", "delivery_type": "Task"}, "Finance & Accounting": {"title": "KPI Analizi (Fin_FinancialAnalysis)", "resource": "https://www.smartsheet.com/content/kpi-dashboard-templates", "delivery_type": "Task"}}
DEPT_COMP1_02	Dept_Comp1	Department	Coaching	Medium	2	2.00	2.90	{"Operations": {"title": "Planlama Checklist", "resource": "https://www.process.st/templates/operational-checklist/", "delivery_type": "Checklist"}, "Technology": {"title": "Kod İnceleme Checklist", "resource": "https://github.com/mgreiler/code-review-checklist", "delivery_type": "Checklist"}, "Human Resources": {"title": "İşe Alım Checklist", "resource": "https://resources.workable.com/tutorial/the-recruitment-process", "delivery_type": "Checklist"}, "Sales & Marketing": {"title": "Satış Görüşmesi Checklist", "resource": "https://www.salesforce.com/ca/blog/sales-call-pre-call-checklist/", "delivery_type": "Checklist"}, "Finance & Accounting": {"title": "Kontrol Checklist", "resource": "https://www.ey.com/en_gl/services/ifrs/accounting-reporting-checklists", "delivery_type": "Checklist"}}
DEPT_COMP1_03	Dept_Comp1	Department	MicroLearning	Easy	2	3.00	4.00	{"Operations": {"title": "Planlama 101", "resource": "https://www.coursera.org/learn/wharton-operations", "delivery_type": "Course"}, "Technology": {"title": "Kod Kalitesi", "resource": "https://www.pluralsight.com/courses/writing-clean-code-humans", "delivery_type": "Course"}, "Human Resources": {"title": "Mülakat Akışı", "resource": "https://www.coursera.org/learn/recruiting-hiring-onboarding-employees", "delivery_type": "Course"}, "Sales & Marketing": {"title": "Satış Temelleri", "resource": "https://www.udemy.com/course/master-successful-selling/", "delivery_type": "Course"}, "Finance & Accounting": {"title": "Veri Okuma", "resource": "https://www.coursera.org/learn/financial-accounting-basics", "delivery_type": "Course"}}
DEPT_COMP2_01	Dept_Comp2	Department	Simulation	Hard	5	1.00	1.90	{"Operations": {"title": "Teslimat Senaryosu", "resource": "https://www.edx.org/learn/supply-chain-design/massachusetts-institute-of-technology-supply-chain-fundamentals", "delivery_type": "Exercise"}, "Technology": {"title": "Ölçeklenebilir Sistem Senaryosu", "resource": "https://github.com/donnemartin/system-design-primer", "delivery_type": "Exercise"}, "Human Resources": {"title": "Disiplin Süreci Senaryosu", "resource": "https://www.shrm.org/topics-tools/tools/forms/discipline-written-warning", "delivery_type": "Exercise"}, "Sales & Marketing": {"title": "Pazarlık Senaryosu", "resource": "https://www.udemy.com/course/a-practical-guide-to-negotiating/", "delivery_type": "Exercise"}, "Finance & Accounting": {"title": "Hata Bulma Senaryosu", "resource": "https://corporatefinanceinstitute.com/course/learn-accounting-fundamentals-corporate-finance/", "delivery_type": "Exercise"}}
DEPT_COMP2_02	Dept_Comp2	Department	MicroLearning	Medium	4	2.00	2.90	{"Operations": {"title": "Lojistik Süreçleri", "resource": "https://www.coursera.org/learn/supply-chain-logistics", "delivery_type": "Course"}, "Technology": {"title": "Sistem Tasarımı", "resource": "https://www.udacity.com/course/software-architect--nd772", "delivery_type": "Course"}, "Human Resources": {"title": "İş Hukuku", "resource": "https://www.coursera.org/learn/employment-law-for-managers", "delivery_type": "Course"}, "Sales & Marketing": {"title": "Müzakere Stratejileri", "resource": "https://www.coursera.org/learn/negotiation-skills", "delivery_type": "Course"}, "Finance & Accounting": {"title": "Muhasebe İlkeleri", "resource": "https://www.coursera.org/specializations/financial-reporting", "delivery_type": "Course"}}
DEPT_COMP2_03	Dept_Comp2	Department	Reflection	Easy	2	3.00	4.00	{"Operations": {"title": "Lojistik Değerlendirme", "resource": "https://miro.com/templates/supply-chain-diagram/", "delivery_type": "Template"}, "Technology": {"title": "Tasarım Değerlendirme", "resource": "https://miro.com/templates/architecture-diagrams/", "delivery_type": "Template"}, "Human Resources": {"title": "Politika Değerlendirme", "resource": "https://miro.com/templates/career-resources/", "delivery_type": "Template"}, "Sales & Marketing": {"title": "Müzakere Değerlendirme", "resource": "https://miro.com/templates/sales-plan/", "delivery_type": "Template"}, "Finance & Accounting": {"title": "Muhasebe Değerlendirme", "resource": "https://miro.com/templates/financial-statement-presentation/", "delivery_type": "Template"}}
DEPT_COMP3_01	Dept_Comp3	Department	Coaching	Hard	4	1.00	1.90	{"Operations": {"title": "Süreç Koçluğu", "resource": "https://www.atlassian.com/agile/project-management/continuous-improvement", "delivery_type": "Checklist"}, "Technology": {"title": "Test Planı Koçluğu", "resource": "https://www.guru99.com/test-planning.html", "delivery_type": "Checklist"}, "Human Resources": {"title": "Zor Çalışan Koçluğu", "resource": "https://hbr.org/podcast/2020/09/coaching-problem-employees", "delivery_type": "Checklist"}, "Sales & Marketing": {"title": "CRM Koçluğu", "resource": "https://www.hubspot.com/hubfs/CRM%20Implementation%20Checklist%20-%20Last%20Updated%20Aug%202023%20%281%29.pdf", "delivery_type": "Checklist"}, "Finance & Accounting": {"title": "Bordro İnceleme", "resource": "https://www.adp.com/resources/articles-and-insights/articles/p/payroll-checklist.aspx", "delivery_type": "Checklist"}}
DEPT_COMP3_02	Dept_Comp3	Department	MicroLearning	Medium	3	2.00	2.90	{"Operations": {"title": "Optimizasyon", "resource": "https://www.coursera.org/learn/operations-management-quality-and-supply-chain", "delivery_type": "Course"}, "Technology": {"title": "QA Süreçleri", "resource": "https://www.udacity.com/course/test-driven-development--cd14599", "delivery_type": "Course"}, "Human Resources": {"title": "Çalışan İlişkileri", "resource": "https://www.coursera.org/learn/employee-relations", "delivery_type": "Course"}, "Sales & Marketing": {"title": "CRM Temelleri", "resource": "https://www.coursera.org/learn/customer-relationship-management", "delivery_type": "Course"}, "Finance & Accounting": {"title": "Bordro Süreci", "resource": "https://www.udemy.com/course/payroll-management/", "delivery_type": "Course"}}
DEPT_COMP3_03	Dept_Comp3	Department	MicroLearning	Medium	3	3.00	4.00	{"Operations": {"title": "Süreç Quiz", "resource": "https://sixsigmastudyguide.com/six-sigma-practice-exams/", "delivery_type": "Course"}, "Technology": {"title": "QA Quiz", "resource": "https://istqb.org/certifications/certified-tester-foundation-level-agile-tester-ctfl-at/", "delivery_type": "Course"}, "Human Resources": {"title": "Employee Relations Quiz", "resource": "https://www.shrm.org/credentials/certification/practice-questions", "delivery_type": "Course"}, "Sales & Marketing": {"title": "CRM Quiz", "resource": "https://academy.hubspot.com/courses/inbound-sales", "delivery_type": "Course"}, "Finance & Accounting": {"title": "Bordro Quiz", "resource": "https://www.accountingcoach.com/payroll-accounting/quiz", "delivery_type": "Course"}}
ROLE_COMP1_01	Role_Comp1	Role	Simulation	Hard	6	1.00	1.90	{"Accountant": {"title": "Finansal Model Simülasyonu", "resource": "https://corporatefinanceinstitute.com/resources/financial-modeling/financial-modeling-test/", "delivery_type": "Exercise"}, "HR Specialist": {"title": "Dokümantasyon Simülasyonu", "resource": "https://www.shrm.org/topics-tools/tools/how-to-guides", "delivery_type": "Exercise"}, "Data Scientist": {"title": "Model Simülasyonu", "resource": "https://www.kaggle.com/competitions/titanic", "delivery_type": "Exercise"}, "Sales Executive": {"title": "Kapanış Simülasyonu", "resource": "https://trailhead.salesforce.com/content/learn/trails/learn-sales-cloud-fundamentals", "delivery_type": "Exercise"}, "Software Engineer": {"title": "Hata Ayıklama Simülasyonu", "resource": "https://github.com/topics/coding-challenges", "delivery_type": "Exercise"}, "Operations Manager": {"title": "Planlama Simülasyonu", "resource": "https://www.edx.org/learn/operations-management/indian-institute-of-management-bangalore-operations-management", "delivery_type": "Exercise"}}
ROLE_COMP1_02	Role_Comp1	Role	PracticalTask	Medium	4	2.00	2.90	{"Accountant": {"title": "Defter Tutma Görevi", "resource": "https://www.accountingcoach.com/bookkeeping/quiz", "delivery_type": "Task"}, "HR Specialist": {"title": "Dokümantasyon Görevi", "resource": "https://www.shrm.org/topics-tools/tools/policies", "delivery_type": "Task"}, "Data Scientist": {"title": "Veri Model Görevi", "resource": "https://paperswithcode.com/sota", "delivery_type": "Task"}, "Sales Executive": {"title": "Pipeline Yönetimi", "resource": "https://blog.hubspot.com/sales/sales-strategy-template", "delivery_type": "Task"}, "Software Engineer": {"title": "Problem Parçalama", "resource": "https://github.com/walljt/architecture-katas", "delivery_type": "Task"}, "Operations Manager": {"title": "Operasyon Görevi", "resource": "https://www.smartsheet.com/content/operational-plan-templates", "delivery_type": "Task"}}
ROLE_COMP1_03	Role_Comp1	Role	MicroLearning	Easy	2	3.00	4.00	{"Accountant": {"title": "Muhasebe Eğitimi", "resource": "https://www.coursera.org/learn/financial-accounting-basics", "delivery_type": "Course"}, "HR Specialist": {"title": "Dokümantasyon Eğitimi", "resource": "https://www.coursera.org/learn/managing-human-resources", "delivery_type": "Course"}, "Data Scientist": {"title": "Veri Bilimi Eğitim", "resource": "https://www.coursera.org/specializations/machine-learning-introduction", "delivery_type": "Course"}, "Sales Executive": {"title": "Satış Eğitimi", "resource": "https://academy.hubspot.com/courses/inbound-sales", "delivery_type": "Course"}, "Software Engineer": {"title": "Mimari Eğitim", "resource": "https://www.pluralsight.com/courses/developer-to-architect", "delivery_type": "Course"}, "Operations Manager": {"title": "Yönetim Eğitimi", "resource": "https://www.coursera.org/learn/wharton-operations", "delivery_type": "Course"}}
ROLE_COMP2_01	Role_Comp2	Role	PracticalTask	Medium	3	1.00	1.90	{"Accountant": {"title": "Mevzuat Görevi", "resource": "https://corporatefinanceinstitute.com/resources/templates/", "delivery_type": "Task"}, "HR Specialist": {"title": "İç Destek Görevi", "resource": "https://www.shrm.org/topics-tools/tools/how-to-guides", "delivery_type": "Task"}, "Data Scientist": {"title": "Model Yorumlama", "resource": "https://www.kaggle.com/learn/machine-learning-explainability", "delivery_type": "Task"}, "Sales Executive": {"title": "CRM Görevi", "resource": "https://www.salesforce.com/sales/pipeline/management/", "delivery_type": "Task"}, "Software Engineer": {"title": "Mimari Görev", "resource": "https://github.com/tedneward/ArchKatas", "delivery_type": "Task"}, "Operations Manager": {"title": "İzleme Görevi", "resource": "https://www.process.st/templates/operational-checklist/", "delivery_type": "Task"}}
ROLE_COMP2_02	Role_Comp2	Role	Coaching	Medium	2	2.00	2.90	{"Accountant": {"title": "Mevzuat Koçluk", "resource": "https://www.aicpa-cima.com/resources/article/tips-for-a-successful-first-month-end-close", "delivery_type": "Checklist"}, "HR Specialist": {"title": "İç Destek Koçluk", "resource": "https://www.shrm.org/topics-tools/tools/how-to-guides", "delivery_type": "Checklist"}, "Data Scientist": {"title": "Model Koçluk", "resource": "https://developers.google.com/machine-learning/crash-course/production-ml-systems", "delivery_type": "Checklist"}, "Sales Executive": {"title": "CRM Koçluk", "resource": "https://blog.hubspot.com/sales/sales-coaching", "delivery_type": "Checklist"}, "Software Engineer": {"title": "Mimari Koçluk", "resource": "https://github.com/mgreiler/code-review-checklist", "delivery_type": "Checklist"}, "Operations Manager": {"title": "İzleme Koçluk", "resource": "https://www.process.st/templates/operational-checklist/", "delivery_type": "Checklist"}}
ROLE_COMP2_03	Role_Comp2	Role	Reflection	Easy	1	3.00	4.00	{"Accountant": {"title": "Mevzuat Şablon", "resource": "https://miro.com/templates/budget/", "delivery_type": "Template"}, "HR Specialist": {"title": "İç Destek Şablonu", "resource": "https://miro.com/templates/retrospective/", "delivery_type": "Template"}, "Data Scientist": {"title": "Model Şablon", "resource": "https://miro.com/templates/data-mapping/", "delivery_type": "Template"}, "Sales Executive": {"title": "CRM Şablon", "resource": "https://miro.com/templates/marketing-funnel/", "delivery_type": "Template"}, "Software Engineer": {"title": "Mimari Şablon", "resource": "https://miro.com/templates/architecture-diagrams/", "delivery_type": "Template"}, "Operations Manager": {"title": "İzleme Şablon", "resource": "https://miro.com/templates/lean-canvas/", "delivery_type": "Template"}}